"""add_finance_indexes

Revision ID: 86ffbb28fd1d
Revises: a00554332e2b
Create Date: 2026-05-28 19:23:11.264902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ffbb28fd1d'
down_revision: Union[str, Sequence[str], None] = 'a00554332e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_budgets_user_id', 'budgets', ['user_id'], unique=False)
    op.create_index('ix_finance_accounts_user_id', 'finance_accounts', ['user_id'], unique=False)
    op.create_index('ix_finance_categories_user_id', 'finance_categories', ['user_id'], unique=False)
    op.create_index('ix_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_budget_id', 'transactions', ['budget_id'], unique=False)
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_index('ix_transactions_budget_id', table_name='transactions')
    op.drop_index('ix_transactions_account_id', table_name='transactions')
    op.drop_index('ix_finance_categories_user_id', table_name='finance_categories')
    op.drop_index('ix_finance_accounts_user_id', table_name='finance_accounts')
    op.drop_index('ix_budgets_user_id', table_name='budgets')
    # ### end Alembic commands ###
